---
title: "Presentation Results"
author: "Matt Kosko"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(data.table)
library(ggplot2)

source('/Users/macbookair/Documents/Projects/cblb/code/helper_funcs.R')
homedir <- '/Users/macbookair/Documents/Projects/cblb'

te <- 0.8
sigma <- 1
degree1 <- 1
degree2 <- 1
k1 <- "poly"
k2 <- "poly"
operator <- "single" # here i'm considering a simple linear kernel just for comparison/true model
penal <- log(2) # keep it between 0.1 and log(k) where k is the number of features

base_nm <- 'aipw_kernel_balancing'
dat_path <- 'data'

# Create the temporary directory
temp_dir <- file.path(homedir, dat_path, paste0(base_nm, '_tmp'))

full <- readRDS(file.path(temp_dir, 'bootstrap.rds'))
cblb <- readRDS(file.path(temp_dir, 'disjoint_subsets.rds'))

```

```{r}
cat("Coverage from the full bootstrap and Wald interval")
full[, .(coverage = mean(lower_ci <= te & upper_ci >= te)), by = c('n', 'type')]
```

```{r}
cat("Coverage from the BLB")
cblb[, .(coverage = mean(lower_ci <= te & upper_ci >= te)), by = c('n', 'gamma', 'subsets', 'out_form', 'prop_form', 'B')]
```

# Timing


```{r}
replications <- 25

base_nm <- 'aipw_kernel_balancing_timing'
dat_path <- 'data'
temp_dir <- file.path(homedir, dat_path, paste0(base_nm, '_tmp'))

full <- readRDS(file.path(temp_dir, 'bootstrap.rds'))
cblb <- readRDS(file.path(temp_dir, 'disjoint_subsets.rds'))

full[, `:=`(type = paste0('Full'))]
cblb[, `:=`(type = paste0('BLB, subsets = ', subsets, ', gamma = ', gamma))]
cblb[, `:=`(gamma = NULL, subsets = NULL)]

timing <- rbindlist(list(cblb, full))
```

```{r}
n <- c(1000, 10000)
for(i in n){
  filt <- timing[n == i]
  p <- ggplot(filt, aes(x = type, y = time_elapsed)) +
  geom_boxplot() +
  ggtitle(paste0('n = ', i)) +
  ylab('Time Elapsed (seconds)') +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
  
  print(p)
}

```

