---
title: "OSQP Kernel Approximations"
author: "Matt Kosko"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(data.table)

source('/Users/macbookair/Documents/Projects/cblb/code/helper_funcs.R')
homedir <- '/Users/macbookair/Documents/Projects/cblb'

te <- 0.8
sigma <- 1

base_nm <- 'approx_kernel_balancing'
dat_path <- 'data'

# Create the temporary directory
temp_dir <- file.path(homedir, dat_path, paste0(base_nm, '_tmp'))

correct <- readRDS(file.path(temp_dir, 'bootstrap_approx.rds'))
full <- readRDS(file.path(temp_dir, 'full_bootstrap_approx.rds'))
cblb <- readRDS(file.path(temp_dir, 'disjoint_subsets.rds'))

```


```{r}
cat("Coverage from the full bootstrap, refitting in each sample", '\n')
correct[, .(mean(lower_ci <= te & upper_ci >= te)), by = c('n', 'type')]
cat("Coverage from the CBLB", "\n")
cblb[, .(mean(lower_ci <= te & upper_ci >= te)), by = c('n', 'gamma', 'subsets', 'out_form', 'prop_form', 'B')]
cat("Coverage from the full bootstrap without refitting", "\n")
full[, .(mean(lower_ci <= te & upper_ci >= te)), by = c('n', 'type')]
```


